library(dplyr)

#Differential APA events were obtained by comparing the differentiated lineages with HSC/MPPs
cluster = c("HSC/MPP","Myeloid progenitor","Immature GMP","Early GMP",
    "Intermediate GMP","Late GMP","MDP","EBM","MEP","Erythroid progenitor","Lymphoid progenitor",
    "MLP","Early BNK","Late BNK")
#The following variables are obtained from the outputs generated by scDaPars
data=read.table('./scDaPars_result/scDaPars_imputed_results.txt')
meta=read.table('./scDaPars_result/meta.txt')
info=read.table('./gene_info.txt')

#Defining the differentiated hematopoietic lineages
data = cbind(cluster = meta$cluster, lineage = meta$cluster,data)
Mye = c("Myeloid progenitor","Immature GMP","Early GMP","Intermediate GMP","Late GMP","MDP","EBM")
Ery = c("MEP","Erythroid progenitor")
Lym = c("Lymphoid progenitor", "MLP","Early BNK","Late BNK")
data$lineage[data$lineage %in% Mye] = 'Mye'
data$lineage[data$lineage %in% Ery] = 'Ery'
data$lineage[data$lineage %in% Lym] = 'Lym'
data$lineage[data$lineage == 'HSC/MPP'] = 'HSC_MPP'

#Lineages were compared with HSC/MPPs to define differential APA events
path = './scDaPars_result/'
myout=function(x,y){
    dt=data.frame()
    for (i in colnames(data[,-1])){
        s = data.frame(gene = data[,i])
        s$cluster = data$cluster
        s = s[s$cluster %in% c(x,y),] 
        s = group_by(s,cluster)
        mean = summarise(s,mean = mean(gene))
        diff_mean = mean[which(mean$cluster == x),'mean'] - mean[which(mean$cluster == y),'mean'] #dataframe
        m = data.frame(gene = i,compare = paste0(x,'_vs_',y), diff_mean = diff_mean$mean,
            p_value = wilcox.test(gene ~ cluster, data = s)$p.value)
        dt = rbind(m,dt)
    }
    dt$fdr <- p.adjust(dt$p_value, method = "BH")
    dt_filter = dt[which(abs(dt$diff_mean) >= 0.2 & dt$fdr <= 0.05),]
    info_dt = info[which(info$ens %in% dt_filter$gene),]
    colnames(dt_filter)[1] = 'ens'
    dt_filter = merge(dt_filter,info_dt,by='ens',all = T)
    dt_filter[which(dt_filter$diff_mean >= 0.2),'UTR'] = 'lengthen'
    dt_filter[which(dt_filter$diff_mean <= -0.2),'UTR'] = 'shorten'
    write.csv(dt_filter, file = paste0(path, x,'_vs_',y,'_APA_events_filter.csv'))
    return(dt_filter)
}

myout("Mye","HSC_MPP")
myout("Lym","HSC_MPP")
myout("Ery","HSC_MPP")

#Merge differential APA events
df_events = data.frame()
for i in c('Mye','Lym','Ery'){
    events = read.csv(path,'lineage_',i'_vs_HSC_MPP_APA_events.csv', row.names=1)
    df_events = rbind(events, df_events)
}
write.csv(df_events, file = paste0(path, 'lineage_compare_APA_events.csv'))